# Default values for application.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

  ingressClassName: "internal-nginx"

  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-internal"

  hosts:
    - host: dev-internal-artemis.tanzdmtr.com
      paths:
        - path: /
          pathType: Prefix

  tls:
    - secretName: dev-artemis-tls
      hosts:
        - dev-internal-artemis.tanzdmtr.com

httpRoute:
  enabled: false

  annotations: {}

  parentRefs:
    - name: gateway
      sectionName: http

  hostnames:
    - chart-example.local

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
